server:
  port: 8080

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      discovery.locator:
        enabled: false
        lowerCaseServiceId: true
      # http://localhost:8080/dummy-userms/users -> http://localhost:8081/users
      routes:
        - id: usermsid
          uri: lb://USERMS
          predicates:
            - Path= /dummy-userms/**
          filters:
            - RewritePath= /dummy-userms/(?<path>.*), /$\{path}

        - id: registrationmsid
          uri: lb://REGISTERMS
          predicates:
            - Path= /dummy-registrationms/**
          filters:
            - RewritePath= /dummy-registrationms/(?<path>.*), /$\{path}

        - id: ordermsid
          uri: lb://ORDERMS
          predicates:
            - Path= /dummy-orderms/**
          filters:
            - RewritePath= /dummy-orderms/(?<path>.*), /$\{path}



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


management:
  endpoints:
    web:
      exposure:
        include: '*'

